---
- hosts: all
  tasks:
  # - name: Upgrade all apt packages
  #   apt: upgrade=dist force_apt_get=yes
  #   become: yes

  - name: Install prerequisites for Docker repository
    apt:
      name: ['ca-certificates', 'curl', 'gnupg', 'lsb-release']
      update_cache: yes
    become: yes

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
    become: yes

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    become: yes

  - name: Install Docker CE
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      update_cache: yes
    become: yes

  - name: Print username
    ansible.builtin.debug:
      msg:  "{{ ansible_user_id }}" 

  - name: Change docker.sock file permission
    file:
      path: /var/run/docker.sock
      owner: "{{ ansible_user_id }}"
    become: yes